"""empty message

Revision ID: 25da33961b92
Revises: d8fa17ccf328
Create Date: 2024-04-29 18:29:19.872822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25da33961b92'
down_revision = 'd8fa17ccf328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_vocab', schema=None) as batch_op:
        batch_op.add_column(sa.Column('definition', sa.Text(), nullable=False))
        batch_op.create_foreign_key(None, 'dictionary_entry', ['definition'], ['definition'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_vocab', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('definition')

    # ### end Alembic commands ###
