"""empty message

Revision ID: 482b364ae701
Revises: 07df0b353d6d
Create Date: 2024-04-29 18:45:38.354899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482b364ae701'
down_revision = '07df0b353d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_vocab', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('definition', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('inflection', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_vocab', schema=None) as batch_op:
        batch_op.drop_column('inflection')
        batch_op.drop_column('definition')
        batch_op.drop_column('word')

    # ### end Alembic commands ###
