"""empty message

Revision ID: 4aef1e008cc4
Revises: 25da33961b92
Create Date: 2024-04-29 18:30:00.377450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aef1e008cc4'
down_revision = '25da33961b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_vocab', schema=None) as batch_op:
        batch_op.add_column(sa.Column('definition', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'dictionary_entry', ['definition'], ['definition'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_vocab', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('definition')

    # ### end Alembic commands ###
