services:
  web:
    build: .
    ports:
     - "5000:5000"
    environment:
      - SECRET_KEY=/eql!Xnd$eco>vP
      - DATABASE_URL=postgresql://myuser:mypassword@db/mydatabase
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
